<a href="https://colab.research.google.com/github/stoicsapien1/ERA/blob/master/MY%20PRACTICE/NUMPY%20AND%20TENSOR/PyTorch%20Tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## PyTorch Tensor

YT Link:https://www.youtube.com/watch?v=x9JiIFvlUwk

In [6]:
device = "cuda" if torch.cuda.is_available() else "cpu"

In [7]:
my_tensor = torch.tensor([[1,2,3],[4,5,6]],dtype=torch.float,device = device)
print(my_tensor)

tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [8]:
print(my_tensor.dtype)

torch.float32


In [9]:
print(my_tensor.device)

cpu


In [10]:
print(my_tensor.shape)

torch.Size([2, 3])


In [11]:
print(my_tensor.requires_grad)

False


# Other common initialization method

In [12]:
x = torch.empty(size = (3,3))

In [13]:
print(x)

tensor([[0.0000e+00, 0.0000e+00, 3.9895e-42],
        [3.9923e-42, 2.6625e-44, 1.8217e-44],
        [1.7516e-43, 9.8091e-45, 0.0000e+00]])


In [17]:
y = torch.zeros((3,3))
print(y)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [18]:
z = torch.rand((3,3))
print(z)

tensor([[0.2550, 0.0571, 0.2792],
        [0.2693, 0.6861, 0.1155],
        [0.2146, 0.4995, 0.3862]])


In [19]:
w = torch.ones((3,3))
print(w)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [21]:
u = torch.eye(5,5)
u

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [24]:
v = torch.arange(start=0,end=5,step=1)
print(v)

tensor([0, 1, 2, 3, 4])


In [26]:
b = torch.linspace(start=0.1,end=1,steps=10)
b

tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])

In [28]:
n = torch.empty(size = (1,5)).normal_(mean=0,std=1)
n

tensor([[-0.5198, -1.1136, -1.9129, -0.0179, -1.8190]])

In [31]:
x =torch.empty(size=(1,5)).uniform_(0,1)

In [32]:
x

tensor([[0.3879, 0.4134, 0.8113, 0.2395, 0.0533]])

In [33]:
x = torch.diag(torch.ones(3))

In [34]:
x

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

# How to initialize and convert tensors to other types